import type { BackendMode, Capability, FeatureGroup, ProviderStatus } from "./domain.js";

interface FeatureDefinition {
  id: string;
  group: FeatureGroup;
  title: string;
  preferredBackend: Capability["preferredBackend"];
  notes: string;
  supportedModes: BackendMode[];
}

export const FEATURE_DEFINITIONS: FeatureDefinition[] = [
  {
    id: "get_daily_summary",
    group: "diary",
    title: "Read daily nutrition summary",
    preferredBackend: "terra",
    supportedModes: ["mock", "terra"],
    notes: "Use Terra for synced nutrition data, or CSV exports for official snapshots.",
  },
  {
    id: "list_food_entries",
    group: "diary",
    title: "List food and recipe entries",
    preferredBackend: "terra",
    supportedModes: ["mock", "terra"],
    notes: "Terra advertises user-input meals; CSV export can also cover this.",
  },
  {
    id: "list_exercises",
    group: "diary",
    title: "List exercises",
    preferredBackend: "terra",
    supportedModes: ["mock", "terra"],
    notes: "Available through Terra or Cronometer CSV export.",
  },
  {
    id: "list_biometrics",
    group: "diary",
    title: "List biometrics",
    preferredBackend: "terra",
    supportedModes: ["mock", "terra"],
    notes: "Available through Terra or Cronometer CSV export.",
  },
  {
    id: "list_notes",
    group: "diary",
    title: "List diary notes",
    preferredBackend: "csv",
    supportedModes: ["mock"],
    notes: "Official export can include notes; browser fallback can inspect current UI.",
  },
  {
    id: "search_foods",
    group: "foods",
    title: "Search Cronometer foods",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "No public food-search API found; browser selectors must be verified.",
  },
  {
    id: "resolve_recipe_ingredients",
    group: "foods",
    title: "Resolve recipe ingredients",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Searches Cronometer for every ingredient before creating a custom recipe.",
  },
  {
    id: "suggest_food",
    group: "foods",
    title: "Suggest food",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Suggest Food. Submission should require confirmation.",
  },
  {
    id: "ask_oracle",
    group: "foods",
    title: "Ask the Oracle",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods. Framework-only until the UI flow is verified.",
  },
  {
    id: "log_food",
    group: "logging",
    title: "Log food",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Food logs write directly when server writes are enabled; use dryRun=true for previews or ambiguity.",
  },
  {
    id: "log_exercise",
    group: "logging",
    title: "Log exercise",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Requires confirmation and browser automation or partner API access.",
  },
  {
    id: "log_biometric",
    group: "logging",
    title: "Log biometric",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Requires confirmation and browser automation or partner API access.",
  },
  {
    id: "log_note",
    group: "logging",
    title: "Log note",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Requires confirmation and browser automation.",
  },
  {
    id: "create_custom_food",
    group: "foods",
    title: "Create custom food",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Requires careful nutrition validation before writing.",
  },
  {
    id: "list_custom_foods",
    group: "foods",
    title: "List custom foods",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Custom Foods.",
  },
  {
    id: "create_custom_meal",
    group: "foods",
    title: "Create custom meal",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Custom Meals. Browser-only until partner API access exists.",
  },
  {
    id: "list_custom_meals",
    group: "foods",
    title: "List custom meals",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Custom Meals.",
  },
  {
    id: "list_custom_recipes",
    group: "foods",
    title: "List custom recipes",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Custom Recipes.",
  },
  {
    id: "create_recipe",
    group: "foods",
    title: "Create custom recipe",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Recipe importer may require Gold. Browser selectors must be verified.",
  },
  {
    id: "get_targets",
    group: "targets",
    title: "Read nutrition targets",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "No public targets API found.",
  },
  {
    id: "set_targets",
    group: "targets",
    title: "Update nutrition targets",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Always require user confirmation.",
  },
  {
    id: "export_data",
    group: "reports",
    title: "Export Cronometer data",
    preferredBackend: "csv",
    supportedModes: ["mock"],
    notes: "Cronometer officially supports CSV export from Account Settings.",
  },
  {
    id: "get_charts",
    group: "reports",
    title: "Read charts",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Trends > Charts.",
  },
  {
    id: "get_nutrition_report",
    group: "reports",
    title: "Read nutrition report",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Trends > Nutrition Report.",
  },
  {
    id: "get_print_report",
    group: "reports",
    title: "Generate print report",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Trends > Print Report.",
  },
  {
    id: "list_snapshots",
    group: "reports",
    title: "List snapshots",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Trends > Snapshots.",
  },
  {
    id: "create_snapshot",
    group: "reports",
    title: "Create snapshot",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Trends > Snapshots. Treat as a write action.",
  },
  {
    id: "start_fast",
    group: "fasting",
    title: "Start fast",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Gold feature in some contexts. Treat as a write action.",
  },
  {
    id: "stop_fast",
    group: "fasting",
    title: "Stop fast",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Gold feature in some contexts. Treat as a write action.",
  },
  {
    id: "schedule_repeat_item",
    group: "scheduling",
    title: "Schedule repeat item",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Gold feature. Browser selectors must be verified.",
  },
  {
    id: "list_repeat_items",
    group: "scheduling",
    title: "List repeat items",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under Foods > Repeat Items.",
  },
  {
    id: "get_profile",
    group: "targets",
    title: "Read targets and profile",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Targets + Profile.",
  },
  {
    id: "set_profile",
    group: "targets",
    title: "Update profile",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Observed under More > Targets + Profile.",
  },
  {
    id: "get_macro_scheduler",
    group: "scheduling",
    title: "Read macro scheduler",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Macro Scheduler.",
  },
  {
    id: "set_macro_scheduler",
    group: "scheduling",
    title: "Update macro scheduler",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Observed under More > Macro Scheduler.",
  },
  {
    id: "get_display_settings",
    group: "capabilities",
    title: "Read display settings",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Display Settings.",
  },
  {
    id: "set_display_settings",
    group: "capabilities",
    title: "Update display settings",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Observed under More > Display Settings.",
  },
  {
    id: "list_devices",
    group: "capabilities",
    title: "List sync devices",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Sync a Device.",
  },
  {
    id: "connect_device",
    group: "capabilities",
    title: "Connect sync device",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Observed CONNECT buttons under More > Sync a Device.",
  },
  {
    id: "get_sharing",
    group: "capabilities",
    title: "Read sharing settings",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Sharing.",
  },
  {
    id: "set_sharing",
    group: "capabilities",
    title: "Update sharing settings",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Write action. Observed under More > Sharing.",
  },
  {
    id: "get_account",
    group: "capabilities",
    title: "Read account settings",
    preferredBackend: "browser",
    supportedModes: ["mock"],
    notes: "Observed under More > Your Account.",
  },
  {
    id: "bulk_delete_entries",
    group: "capabilities",
    title: "Bulk delete entries",
    preferredBackend: "browser",
    supportedModes: [],
    notes: "Dangerous account action observed under Your Account. Keep disabled until a dedicated review flow exists.",
  },
  {
    id: "delete_account",
    group: "capabilities",
    title: "Delete account",
    preferredBackend: "manual",
    supportedModes: [],
    notes: "Dangerous account action observed under Your Account. Intentionally not implemented.",
  },
];

export function capabilitiesForMode(mode: BackendMode): Capability[] {
  return FEATURE_DEFINITIONS.map((feature) => {
    const status: ProviderStatus = feature.supportedModes.includes(mode)
      ? mode === "mock"
        ? "dry_run"
        : "ok"
      : mode === "browser"
        ? "needs_manual_step"
        : "unsupported";

    return {
      id: feature.id,
      group: feature.group,
      title: feature.title,
      preferredBackend: feature.preferredBackend,
      currentBackendStatus: status,
      notes: feature.notes,
    };
  });
}
